### ISSUE TITLE
Wrong variable in Makefile.

### ISSUE THREAD

**Issue by tkovs** [robotlolita/purr#132]
[Here](https://github.com/robotlolita/purr/blob/master/Makefile#L10). Why PACKGE? It should be PACKAGE, right? There are references to PACKAGE, but there is no PACKAGE in _Configuration section_.

**Comment by grsabreu** [comment]
That really seems to be a typing mistake :p

**Comment by tkovs** [comment]
An [old](https://github.com/robotlolita/purr/blob/9902e356403512c1152148d07283ac494a506c56/Makefile#L9) error.

**Comment by robotlolita** [comment]
Ah, yeah, it's generated from a project skeleton, which happened to have that typo :)
